import sqlite3
db=sqlite3.connect('base.db')
cur=db.cursor()
cur.execute("SELECT * FROM user")
print(cur.fetchall())
#cur.execute("DELETE FROM food")
cur.execute("DELETE FROM user")
cur.execute("DELETE FROM admin")
cur.execute("DELETE FROM food")
cur.execute("INSERT INTO food VALUES ('blini',0)")
cur.execute("INSERT INTO food VALUES ('borch',0)")
cur.execute("INSERT INTO food VALUES ('grechka',0)")
cur.execute("INSERT INTO food VALUES ('kasha',0)")
cur.execute("INSERT INTO food VALUES ('kotletka_s_pureshkoy',0)")
cur.execute("INSERT INTO food VALUES ('makaroni',0)")
cur.execute("INSERT INTO food VALUES ('pelmeni',0)")
cur.execute("INSERT INTO food VALUES ('perlovka',0)")
cur.execute("INSERT INTO food VALUES ('sasuges',0)")
cur.execute("INSERT INTO food VALUES ('zapikanka',0)")
cur.execute(f"INSERT INTO user VALUES (?,?,?,?,?,?,?,?)",('Admin','Admin','admin','qwer','11A','Plat',123,123))
cur.execute("DELETE FROM user_eat")
db.commit()
cur.execute("SELECT * FROM user")
print(cur.fetchall())
db.close()